build:
	protoc -I. --go_out=plugins=micro:${GOPATH}/src/github.com/tomekwlod/microservices/consignment-service proto/consignment/consignment.proto

run:
	docker run -p 50051:50051 \
		-e MICRO_SERVER_ADDRESS=:50051 \
		-e MICRO_REGISTRY=mdns \
		consignment-service